### ISSUE TITLE
Could you please add a readme file for this program

### ISSUE THREAD

**Issue by wwmsg** [silkfire/DiamondNeXus2Vamas#1]
Hi Sir/Madam,

Thank you very much for your contribution. I met a problem when I used VS to run your program. I'm using the windows system and I successfully loaded your program, however, when I try to specify the path to the conversion definition file. It always says "[CasaXpsUtilities] ERROR Conversion operation failed → Failed to parse sample information string → Invalid sample information string encountered: ["

Is it possible for you to provide a readme file to show me how to make this works?

Thank you!

**Comment by silkfire** [comment]
@wwmsg  I've added a README to the repo now. Let me know if there's something that's not clear or could use further explanation.
